with: test / ;with in all test.8th
exercism/8th pull request #124
Opened 2024-03-04 07:46 UTC by axtens

CLI-based testing issue reported in https://forum.exercism.org/t/having-trouble-with-8th/10069 

Will take this up with Ron Aaron, that a `with: test` at the end of the `./libs/exercism/test` doesn't appear to work when the file is `needs` included and that the `with: test` is required again in the `test.8th` file itself.

In `hello-world`, the `with: test` at the end of `./libs/exercise/test` appears to be being ignored. Putting `with: test` after the `needs` in `hello-world`'s `test.8th`  makes the `test` namespace visible to the tests in `test.8th`

2024-03-04 13:44 UTC, glennj commented
Right, that totally makes sense.

2024-03-04 13:47 UTC, glennj requested changes

2024-03-04 13:47 UTC, glennj commented on exercises/practice/acronym/acronym.8th
> +  /[^a-zA-Z']/ s:/ ( 0 1 s:slice s:uc ) a:map "" a:join
```suggestion
```
Look like you're putting the solution in the student's download file.

2024-03-04 15:56 UTC, glennj approved these changes

2024-03-05 01:28 UTC, axtens commented
@ErikSchierboom so when the Test/ci fails because I don't have the token `Run actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
Error: Input required and not supplied: token` is it still okay to squash and merge given that the other items subsequent have a tick?

2024-03-05 05:10 UTC, glennj commented
You have to be confident that the changes will pass the tests.

2024-03-05 07:04 UTC, ErikSchierboom commented
> @ErikSchierboom so when the Test/ci fails because I don't have the token Run actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 Error: Input required and not supplied: token is it still okay to squash and merge given that the other items subsequent have a tick?

It's a security/permissions thing. The only reason to workaround this is by creating the PR, not via the fork, but directly on this repo. In other words: to push the branch to this repo and not your fork, and then use that to create the PR from. This should work as you have repo permissions.

2024-03-05 07:05 UTC, ErikSchierboom approved these changes

2024-03-05 12:52 UTC, merged

2024-03-05 12:53 UTC, ErikSchierboom commented
It was almost correct, just acronym failing: https://github.com/exercism/8th/actions/runs/8156564580/job/22294372857