Add `grains` exercise
exercism/8th pull request #142
Opened 2024-04-22 12:35 UTC by ErikSchierboom

2024-04-22 14:39 UTC, axtens commented
1. You need to be specific about which `between` you want, that is which namespace. 
```
ok> help between

d:between (since 22.07)
SED: d1 d2 d3 -- T

Like n:between, but for dates. true if d2 ≤ d1 ≤ d3.

n:between
SED: n low hi -- T

Return true if the number n is between low and hi, inclusive; e.g. if low ≤ n
 ≤ hi.
```
2. In `!if null? ;then` are you testing for null or returning null? If the latter, remove the trailing question mark.
3. `between` will consume your in-coming `n`. You'll need to `dup` it

2024-04-22 18:22 UTC, glennj requested changes

2024-04-22 18:22 UTC, glennj commented on exercises/practice/grains/test.8th
> +    equal?
```suggestion
    null?
```
And the next two tests.

2024-04-22 18:22 UTC, glennj commented on exercises/practice/grains/.meta/example.8th
> +  1 64 between !if null? ;then
As Bruce mentioned, need a `dup` first. And then, if not between, need to `drop` before adding `null` to the stack.
```suggestion
  dup 1 64 between !if drop null ;then
```
As it stands, the `n:1- 2 swap n:^` is operating on the _expected value_: you _should_ be seeing the "PANIC: expected stack depth to be 3" message. Is your main branch up-to-date (or your local copy of the 8th test runner)?

2024-04-22 18:24 UTC, glennj commented on exercises/practice/grains/.meta/example.8th
> +  1 64 between !if null? ;then
Alternately, copy the input to the r-stack:
```forth
: square
  dup>r
  1 64 between !if null ;then
  r> n:1- 2 swap n:^
;
```

2024-04-23 07:33 UTC, ErikSchierboom commented
Not sure what happened there. I thought I had ran `bin/test-no-docker -r grains` to verify, but must have fumbled.

2024-04-23 09:26 UTC, axtens approved these changes

2024-04-23 09:42 UTC, axtens commented
So have you merged this already, @ErikSchierboom ?

2024-04-23 10:13 UTC, ErikSchierboom commented
I haven't because Glenn has requested changes in their review, so I'd like them to confirm I've done the right thing :)

2024-04-23 11:50 UTC, glennj approved these changes
Looks good

2024-04-23 11:50 UTC, merged