knapsack
exercism/8th pull request #183
Opened 2024-05-14 13:38 UTC by ErikSchierboom

- **Add `knapsack` exercise**
- **Work**
- **Tweak names**

2024-05-14 16:57 UTC, glennj commented
I'll try to dig into it this evening.

2024-05-15 00:18 UTC, glennj commented
This might be the same problem with JSON literals that I saw in phone-number: repeating the same sequence produces different results.
```
$ 8th
8th 24.02 LIN64 Free (98b29c8c/2024-03-11) custid: 44e5dc98

ok> "example.8th" f:include

ok> 10 [{"weight": 5, "value": 10}, {"weight": 4, "value": 40}, {"weight": 6, "value": 30}, {"weight": 4, "value": 50}] maximum-value

ok> .s
 0 n: 00007f4c42b93b30 2  90

ok> drop

ok> 10 [{"weight": 5, "value": 10}, {"weight": 4, "value": 40}, {"weight": 6, "value": 30}, {"weight": 4, "value": 50}] maximum-value

ok> .s
 0 n: 00007f4c42b933e0 2  100
```

2024-05-15 00:23 UTC, glennj requested changes

2024-05-15 00:23 UTC, glennj commented on exercises/practice/knapsack/.meta/example.8th
> +  n:1+ [0] swap a:smear
```suggestion
  n:1+ a:new 0 a:push swap a:smear
```
Also, this doesn't appear to be "maximum-values", it appears to be an array of n+1 zeroes

2024-05-15 06:59 UTC, merged

2024-05-15 06:59 UTC, ErikSchierboom commented
Thanks @glennj for your help!

2024-05-15 13:13 UTC, axtens approved these changes

2024-05-15 13:15 UTC, axtens commented
I take all questions like that to the 8th forum. Ron is very helpful