no more array insensitive dots as recent 8th update corrects array to…
exercism/8th pull request #194
Opened 2024-06-02 08:21 UTC by axtens

… string conversion issue

So I thought this had been dealt with. But I was just trying to update my repo to the upstream and go sync error

2024-06-02 12:48 UTC, glennj requested changes

2024-06-02 12:48 UTC, glennj commented on exercises/practice/grains/libs/exercism/test
> -
Too much deleted for grains.

2024-06-02 12:48 UTC, glennj commented on exercises/practice/pythagorean-triplet/libs/exercism/test
> -
too much deleted for pythagorean-triplet

2024-06-02 12:48 UTC, glennj commented on exercises/practice/series/libs/exercism/test
> -
too much deleted for series

2024-06-02 12:48 UTC, glennj commented on exercises/practice/sieve/libs/exercism/test
> -
sieve too

2024-06-02 12:48 UTC, glennj commented on exercises/practice/sum-of-multiples/libs/exercism/test
> -
sum-of-multiples too

2024-06-02 13:36 UTC, axtens commented
Okay, so what's the best way of handling this?

2024-06-02 18:29 UTC, glennj commented
https://github.com/exercism/8th/blob/main/libs/README.md

2024-06-03 12:11 UTC, glennj commented
Did I misunderstand "what's the best way of handling this"? Make the change in `libs/exercism/test` and copy it to the exercises. That way, you minimize editing errors.

2024-06-03 13:38 UTC, axtens commented
I'm not disputing your advice. It's correct. The difficulty is with my understand of the situation. I have a test library in `8th/libs/exercism/test` that has, on line 67-68
```
   \ otherwise fall back to 'lazy evaluation'
   l: =
```
and it is this line that the other exercises are bombing on. So will copying this file to those exercises fix the problem?

2024-06-03 13:39 UTC, axtens commented
I didn't write the test library.

2024-06-03 16:59 UTC, glennj commented
That came from Ron:
https://8th-dev.com/forum/index.php?topic=2745.msg15984#msg15984

I see in the words list:

l: | --
-- | --
  | **IMMEDIATE** _needs utils/latebind_  Makes the next word "delayed lookup". Compiles the string <name> into the word currently being compiled. At runtime, every time the code is invoked, it looks up the word with that name. So l: + will add two numbers, or concatenate two strings, using the same code.

Try adding `needs utils/latebind` to the test file

2024-06-15 14:45 UTC, closed without merging