Triangle
exercism/8th pull request #50
Opened 2022-11-10 08:50 UTC by axtens

2022-11-10 10:37 UTC, ErikSchierboom reviewed
The PR title is not shedding much light on what this PR does. Could you expand a bit on what it does?

2022-11-10 13:51 UTC, axtens commented
Oops. It's supposed to be the exercise for the triangle task. However it's not complete, suggesting that I've PRed too far up the tree.

2022-11-10 13:52 UTC, axtens commented
So if you're able, please delete it

2022-11-10 15:03 UTC, ErikSchierboom commented
PRs can't be deleted, sorry

2022-11-10 23:53 UTC, kotp commented
Probably set it to draft, you can always force push to this branch and adjust the title and then it will be as it should be.  No need to delete.

2022-11-18 03:54 UTC, kotp requested changes
Other than consistency for line endings, looks good to me.

2022-11-18 03:54 UTC, kotp commented on exercises/practice/armstrong-numbers/armstrong-numbers-tests.8th
>  bye
Missing last line, by definition.  This happens 18 times for this patch.

Each file that consists of lines, should have an EOL character for the last intended line.

2022-11-18 04:07 UTC, axtens commented
EOL as in control-Z or just a CRLF at the end of the previous line?

On Fri, 18 Nov 2022 at 11:54, Victor Goff ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> Other than consistency for line endings, looks good to me.
> ------------------------------
>
> In exercises/practice/armstrong-numbers/armstrong-numbers-tests.8th
> <https://github.com/exercism/8th/pull/50#discussion_r1025960398>:
>
> > -\ "There are no 2 digit Armstrong Numbers"    ( 10 armstrong?  ) false test_eq
> -\ "Three digit number that is not an Armstrong number"    ( 100 armstrong?  ) false test_eq
> -\ "Three digit number that is an Armstrong number"    ( 153 armstrong?  ) true test_eq
> -\ "Four digit number that is an Armstrong number"    ( 9474 armstrong?  ) true test_eq
> -\ "Four digit number that is not an Armstrong number"    ( 9475 armstrong?  ) false test_eq
> -\ "Seven digit number that is not an Armstrong number"    ( 9926314 armstrong?  ) false test_eq
> -\ "Seven digit number that is an Armstrong number"    ( 9926315 armstrong?  ) true test_eq
> +"Zero is an Armstrong number"    ( 0 armstrong?  ) test_true
> +\ "Single digit numbers are Armstrong numbers"    ( 5 armstrong?  ) test_true
> +\ "There are no 2 digit Armstrong Numbers"    ( 10 armstrong?  ) test_false
> +\ "Three digit number that is not an Armstrong number"    ( 100 armstrong?  ) test_false
> +\ "Three digit number that is an Armstrong number"    ( 153 armstrong?  ) test_true
> +\ "Four digit number that is an Armstrong number"    ( 9474 armstrong?  ) test_true
> +\ "Four digit number that is not an Armstrong number"    ( 9475 armstrong?  ) test_false
> +\ "Seven digit number that is not an Armstrong number"    ( 9926314 armstrong?  ) test_false
> +\ "Seven digit number that is an Armstrong number"    ( 9926315 armstrong?  ) test_true
>
>  bye
>
> Missing last line, by definition. This happens 18 times for this patch.
>
> Each file that consists of lines, should have an EOL character for the
> last intended line.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/exercism/8th/pull/50#pullrequestreview-1185413603>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AABTFVIG5BH6UTH3T6XGDPDWI34XVANCNFSM6AAAAAAR4JX6FI>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-11-18 08:56 UTC, kotp commented
> EOL as in control-Z or just a CRLF at the end of the previous line?

I believe control-z would give you end of data, not end of line.  The files are using `\n` as shown, `60 60 60 0A` as the last characters for the README while `practice/triangle/triangle_tests.8th` has `62 79 65` as the last, missing the end of line character.  The `0A` hex is `LF`.

I believe you can set your git configuration so that this remains consistent for your changes.

It might be worth setting a `.gitattributes` file in the project so everyone gets the benefit of the settings regarding end of line consistency, as well.

2022-11-19 09:33 UTC, merged